### PR TITLE
always set hostname from metadata service

### PR DESCRIPTION
**Pull request by stuffo**
makes hostname change eg. when renaming droplets

### CODE REVIEW

**Comment by stuffo** [comment]
is there anything wrong with this? should I improve something or are you not going to merge this anyhow?

**Comment by gh2o** [comment]
Hey! I apologize for the late reply. Do you know if this works properly with both simple and DNS (.com etc) hostnames?

**Comment by gh2o** [comment]
I agree with your change; however there should be some way for the user to override this setting; perhaps copying it over from `/etc/hostname.local` or similar.

**Comment by gh2o** [comment]
Closing due to age, please feel free to reopen if relevant.

**Pull request closed without merging**
