### PR TITLE
RFC: pkgbuild: Use a Arch Linux package to install

### PR DESCRIPTION
**Pull request by kylemanna**
Hi all, this is a pretty dramatic change and was sharing if there was any interest.

In a nutshell this replaces the scripts embedded in `install.sh` with an embeded pacman package.  The existing scripts are moved verbatim to the pacman package.  The net result is the same with a few changes:
- Users download and install via `install.pkg.sh` instead of `install.sh`.  The `install.pkg.sh` script is a `install.sh` + base64 appended pacman package.
- Allows for AUR package updates and shares 100% of  the code with that AUR package.
- Would enable package signing for additional security if so desired.

Github releases would be tagged and the `install.pkg.sh` made using the Makefile and then uploaded.

Example release on my fork:
https://github.com/kylemanna/digitalocean-debian-to-arch/releases/tag/v2.4-2

The `README` would need to be updated to change the `wget` path from the raw repository to the tagged release.

Curious if there is any interest in this.  Enjoy!

### CODE REVIEW

**Comment by kylemanna** [comment]
I set up the AUR package @ https://aur4.archlinux.org/packages/digitalocean-synchronize/

One annoyance is that _every_ commit needs to have the `.SRCINFO` file or a push hook declines the push request.  As a result I had to create a `aur` branch with orphaned history. :(

**Comment by gh2o** [comment]
Hello Kyle, thanks for the suggestion and work. I like the idea of having an AUR package too, but for the sake of simplicity, I would prefer not having a build and release process (what's Arch without some bleeding edge)?

Here's my suggestion: keep the files embedded the way it currently is, but do the following:
- Add PKGBUILD, digitalocean-synchronize.service and digitalocean-synchronize.install as embedded files.
- If the script is run with the `--create_pkgbuild=/path/to/dir` flag, the script will populate `/path/to/dir` with the above files.

Let me know what you think!

**Comment by kylemanna** [comment]
I agree about the bleeding edge, but one of the primary goals was to remove the embedded files from the monolithic file for a few reasons:
1. They are a pain to test in isolation (i.e. before committing) to extract or merge changes in external scripts.
2. The commit history is all squashed in to one file and is not modular.
3. Violates the [principal of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for the users that need to debug things.
4. Prevents anyone from maintaining a fork and reusing files.

One alternative might be to commit the `install.pkg.sh`, but I feel that that the version control gods would start crying.

Perhaps https://travis-ci.org could be used to build the package and publish it automatically.

**Comment by gh2o** [comment]
I agree with your points. I'm considering Travis but it seems like it doesn't support deploying to a fixed URL.

**Comment by kylemanna** [comment]
One thought, admittedly hacky, would be to publish to the the assembled `install.pkg.sh` to the `gh-pages` branch.  Perhaps investigate a way to rebase that branch periodically so that the repo doesn't grow without bounds. Travis CI [appears to support pushing to git repos](http://docs.travis-ci.com/user/deployment/custom/) as well. 

Then users could fetch it from `https://gh2o.github.io/digitalocean-debian-to-arch/install.pkg.sh` or something similar.

I envisioned building the package using Docker to bring the Arch Linux build environment necessary for `makepkg`.  Using Docker on travis-ci seem like a number of hacks are required (https://github.com/moul/travis-docker) but https://drone.io might be more straight forward.

**Comment by gh2o** [comment]
Since we're not building any binaries, it's actually quite a bit simpler. I got makepkg to run on Ubuntu with only bsdtar as an additional dependency.

As for the release pushes, we could create an orphaned commit for each release, since the commit history is only relevant on the source branch.

One more option is simply embedding the PKGBUILD, .service and .install files into the release script in the build process and having the droplet run makepkg to build and install the package. That way, all that Travis ever needs to build is the release script.

**Comment by kylemanna** [comment]
Travis added Docker support: http://docs.travis-ci.com/user/docker

This should simplify the build process.  Still need to host the packages somewhere though.

**Comment by gh2o** [comment]
My biggest issue with the Travis + GitHub release approach is that there is no longer a single "master" URL from which the script can be fetched without running an external server since the URL would now contain the version number. The alternative would be to simply drop in a Makefile, manually build the script, and push the build artifact onto a separate branch.

By the way, can you turn off or disable the AUR package for now? I think it might be causing the issues in #21.

**Comment by kylemanna** [comment]
I'll close the pull request and maintain my own fork.  Thanks for consideration!

**Pull request closed without merging**
